Eval - builtins merging
TERMINA-tor/42sh pull request #6
Opened 2024-01-11 20:34 UTC by Drogonito

add of basic builtins (true, false, echo, echo flags)

2024-01-11 21:00 UTC, Matthiaskd commented
tout est parfait, t'as fait une test suite pytest ?

2024-01-11 21:07 UTC, Drogonito commented
nan j'ai fait mes tests dans un fichier .c
builtins_test.c

2024-01-11 21:12 UTC, Matthiaskd commented
en vrai rajoute des tests, c'est vraiment facile à faire, je vais rajouter une partie test_builtin dans les jobs, faudra juste que tu remplaces make check par ta commande de test

2024-01-11 21:15 UTC, Drogonito commented
ok je ferai ca demain du coup. c'est assez rapide je pense et de toute facon je sais que mes tests actuelles et par consequent mes builtins marchent
envie de mourir j'ai passe legit 1h a ecrir mon fichier de test pour devoir le reecrir en python

2024-01-12 09:50 UTC, Matthiaskd requested changes
add test suite

2024-01-12 15:27 UTC, Drogonito commented
tests added, everything should be clean

2024-01-12 15:47 UTC, Matthiaskd commented
adding your test suite right now

2024-01-12 15:53 UTC, Matthiaskd commented
refais une pull request, pour inclure les nouveaux tests

2024-01-12 15:53 UTC, closed without merging